### PR TITLE
Fix service files not merged with shadow plugin

### LINKED ISSUE #406: After upgrading Micronaut Gradle plugin from 3.2.2 to 3.3.0 fat-JAR application launch crashes with No bean of type [io.micronaut.context.event.ApplicationEventPublisher<io.micronaut.context.event.StartupEvent>] exists
### Expected Behavior

Application should launch smoothly like before the upgrade.

### Actual Behaviour

Application's Single-JAR is currently built using following plugin:
`id('com.github.johnrengelman.shadow') version '7.+'`

After upgrading Gradle Micronaut plugin from
`id('io.micronaut.application') version '3.2.2'`
to
`id('io.micronaut.application') version '3.3.0'`
launching the Single-JAR application like so
`java -jar build/libs/application-0.1-all.jar`
breaks with
```
10:16:17.436Z [   main] ERROR - Error starting Micronaut server: No bean of type [io.micronaut.context.event.ApplicationEventPublisher<io.micronaut.context.event.StartupEvent>] exists. Make sure the bean is not disabled by bean requirements (enable trace logging for 'io.micronaut.context.condition' to check) and if the bean is enabled then ensure the class is declared a bean and annotation processing is enabled (for Java and Kotlin the 'micronaut-inject-java' dependency should be configured as an annotation processor).
io.micronaut.context.exceptions.NoSuchBeanException: No bean of type [io.micronaut.context.event.ApplicationEventPublisher<io.micronaut.context.event.StartupEvent>] exists. Make sure the bean is not disabled by bean requirements (enable trace logging for 'io.micronaut.context.condition' to check) and if the bean is enabled then ensure the class is declared a bean and annotation processing is enabled (for Java and Kotlin the 'micronaut-inject-java' dependency should be configured as an annotation processor).
	at io.micronaut.context.DefaultBeanContext.getBeanInternal(DefaultBeanContext.java:2795)
	at io.micronaut.context.DefaultBeanContext.getBean(DefaultBeanContext.java:1654)
	at io.micronaut.context.BeanLocator.getBean(BeanLocator.java:94)
	at io.micronaut.context.DefaultBeanContext.publishEvent(DefaultBeanContext.java:1733)
	at io.micronaut.context.DefaultBeanContext.start(DefaultBeanContext.java:344)
	at io.micronaut.context.DefaultApplicationContext.start(DefaultApplicationContext.java:183)
	at io.micronaut.runtime.Micronaut.start(Micronaut.java:72)
	[...]
```
reproducibly.

With enabled trace logging (as requested) the following message appears just in front of the one cited above:
```
DEBUG - Bean [foo.bar.baz.$OrderStatePublisherHttpClientImpl$Definition$Intercepted$Definition] will not be loaded due to failing conditions:
```

Also explicit addition of mentioned library with Kotlin APT via `kapt('io.micronaut:micronaut-inject-java')` doesn't help.

None of the application's types explicitly implement mentioned interface `io.micronaut.context.event.ApplicationEventPublisher<io.micronaut.context.event.StartupEvent>`.

After switching back to `id('io.micronaut.application') version '3.2.2'` app launches smoothly (with lots of messages regarding bean conditionals due to enabled trace logging of this feature).

### Steps To Reproduce

See above.
```
$ ./gradlew clean assemble && java -jar build/libs/application-0.1-all.jar
```

### Environment Information

* JRE 17.0.2
* Kotlin 1.6.10
* Gradle 7.4.1
* Micronaut 3.3.4

### Example Application

_No response_

### Version

3.3.4

### PR DESCRIPTION
**Pull request by melix**
This commit fixes shadow jar building, by making sure that the generated
jar merges service files.

Fixes #406

### CODE REVIEW

File: functional-tests/src/test/groovy/io/micronaut/gradle/shadow/ShadowJarSpec.groovy [hunk 1]
```diff
@@ -0,0 +1,80 @@
...
+    @Issue("https://github.com/micronaut-projects/micronaut-gradle-plugin/issues/406")
+    def "merges service files when building shadow jar"() {
+        def shadowJar = file("build/libs/hello-world-1.0-all.jar")
+
+        given:
+        settingsFile << "rootProject.name = 'hello-world'"
+        buildFile << """
+            plugins {
+                id "io.micronaut.minimal.application"
+                id "com.github.johnrengelman.shadow" version "7.1.0"
```
Comment (sdelamo) [inline functional-tests/src/test/groovy/io/micronaut/gradle/shadow/ShadowJarSpec.groovy:18]: we currently generate apps using 7.1.2 of shade.

Comment (melix) [reply functional-tests/src/test/groovy/io/micronaut/gradle/shadow/ShadowJarSpec.groovy:18]: Right, it doesn't really matter, it's a test, but I'll upgrade.

**Review by graemerocher — APPROVED** [review]

**Comment by melix** [comment]
I have a couple more fixes I'd like to see in 3.0.1:

- upgrade to native build plugins 0.9.11 to fix issues with building under Windows and fixes with spaces in paths
- upgrade to Micronaut AOT 1.0.0 for classpath fixes

Both need a release first, which make take up to a day (because of internal process for the 1st one).
