### PR TITLE
Fix transitive runtimeClasspath test-resources inference

### LINKED ISSUE #580: Transitive dependencies don't trigger test resources to start
### Expected Behavior

I have a micronaut library that has 

`api("io.micronaut.redis:micronaut-redis-lettuce")`

Therefore, I do NOT specify it explicitly like below in my service using the library

`implementation("io.micronaut.redis:micronaut-redis-lettuce")`

When I look at my IntelliJ extern libs I see redis

Screenshot 2024-04-04 at 5 10 56 PM

## Expected 

I then expect micronaut test resources to start my redis container but it does not

I AM including Kakfa in my repo since the library does not
`implementation("io.micronaut.kafka:micronaut-kafka")`

### Actual Behaviour

```
[test-resources-service] 16:49:32.313 [ForkJoinPool.commonPool-worker-7] INFO  i.m.t.e.TestResourcesResolverLoader - Loaded 2 test resources resolvers: io.micronaut.testresources.kafka.KafkaTestResourceProvider, io.micronaut.testresources.testcontainers.GenericTestContainerProvider
```

### Steps To Reproduce

1. Create a mn library with `api("io.micronaut.redis:micronaut-redis-lettuce")`
2. Include the library via `implementation`
3. Start tests and watch redis not startup

### Environment Information

- MacOs
- JDK 17
- micronaut-tes-resources 2.3.0

### Example Application

_No response_

### Version

4.2.2

### PR DESCRIPTION
**Pull request by alvarosanchez**
## Summary

Closes micronaut-projects/micronaut-test-resources#580

- Traverse resolved `runtimeClasspath` subgraphs behind direct project dependencies when inferring test-resources modules.
- Preserve the existing direct external dependency path and only materialize resolved `ModuleComponentIdentifier` entries as Maven coordinates.
- Add a multi-project regression sample and spec covering direct Kafka plus Redis exported transitively through `project(":lib")`.

## Context

The original reporter-facing issue was filed in `micronaut-test-resources`, but QA traced the executable fix surface to `micronaut-gradle-plugin`, so this PR keeps that cross-repository intake history explicit.

QA originally targeted the Micronaut organization project `5.0.0 Release`. That project no longer exists; the current matching open release board is `5.0.0-M3`.

## Test plan

- [x] `./gradlew :micronaut-test-resources-plugin:test --tests 'io.micronaut.gradle.testresources.MultiProjectTestResourcePluginSpec.detects transitive runtime classpath modules from project dependencies' --rerun-tasks`
- [x] `./gradlew :micronaut-test-resources-plugin:test --tests 'io.micronaut.gradle.testresources.MultiProjectTestResourcePluginSpec'`

---

### CODE REVIEW

**Review by melix — CHANGES_REQUESTED** [review]
The bug is indeed there, `getAllDependencies` does not resolve, so it wouldn't see transitive dependencies. However I think the way it's fixed is wrong. It should use `configuration.getIncoming().getResolutionResult()` instead: there's no need to merge project dependencies with module dependencies: there's a single graph, let's use it.

File: test-resources-plugin/src/main/java/io/micronaut/gradle/testresources/MicronautTestResourcesPlugin.java [hunk 1]
```diff
@@ -325,23 +323,10 @@ private Provider<List<Dependency>> buildTestResourcesDependencyList(Project proj
...
-                        .get()
-                        .getDependencies()
-                        .stream()
-                        .filter(ResolvedDependencyResult.class::isInstance)
-                        .map(ResolvedDependencyResult.class::cast)
-                        .map(ResolvedDependencyResult::getSelected)
-                        .filter(component -> component.getId() instanceof ProjectComponentIdentifier)
-                        .flatMap(component -> collectResolvedModuleDependencies(component, new HashSet<>()));
-                mavenDependencies = concat(directDependencies, projectDependencies)
+                        .get(), new HashSet<>())
```
Comment (melix) [inline test-resources-plugin/src/main/java/io/micronaut/gradle/testresources/MicronautTestResourcesPlugin.java:329]: That `.get()` is suspicious, but maybe fine. I would double check that it actually passes with `--configuration-cache` enabled.

**Review by melix — APPROVED** [review]

File: test-resources-plugin/src/main/java/io/micronaut/gradle/testresources/MicronautTestResourcesPlugin.java (hunk 1 above)
Comment (alvarosanchez) [reply test-resources-plugin/src/main/java/io/micronaut/gradle/testresources/MicronautTestResourcesPlugin.java:329]: Verified as requested: the targeted regression passes with `--configuration-cache`, and a follow-up run reuses the configuration cache successfully. No code change needed for this `.get()`.

---
###### ✨ This message was AI-generated using gpt-5.5
