### PR TITLE
Replace lambda with AIC

### LINKED ISSUE #473: Execution optimisations error with 3.4.0 when running continuously
### Expected Behavior

No error

### Actual Behaviour

```
Execution optimizations have been disabled for task ':run' to ensure correctness due to the following reasons:
  - Additional action of task ':run' was implemented by the Java lambda 'io.micronaut.gradle.MicronautMinimalApplicationPlugin$$Lambda$3309/0x0000000801d94e98'. Reason: Using Java lambdas is not supported as task inputs. Please refer to https://docs.gradle.org/7.4.2/userguide/validation_problems.html#implementation_unknown for more details about this problem.
```

### Steps To Reproduce

Use ./gradlew run -t

### Environment Information

_No response_

### Example Application

_No response_

### Version

3.4.0

### PR DESCRIPTION
**Pull request by melix**
Lambdas as task actions are not properly tracked by Gradle.

Fixes #473

### CODE REVIEW

File: minimal-plugin/src/main/java/io/micronaut/gradle/MicronautMinimalApplicationPlugin.java [hunk 1]
```diff
@@ -102,14 +103,17 @@ private void configureJavaExecTasks(Project project, Configuration developmentOn
...
                     sysProps.put("micronaut.io.watch.enabled", true);
-                    javaExec.doFirst(workaroundEagerSystemProps -> {
-                        String watchPaths = sourceSet
-                                .getAllSource()
-                                .getSrcDirs()
-                                .stream()
-                                .map(File::getPath)
-                                .collect(Collectors.joining(","));
-                        javaExec.systemProperty("micronaut.io.watch.paths", watchPaths);
+                    javaExec.doFirst(new Action<Task>() {
```
Comment (graemerocher) [inline minimal-plugin/src/main/java/io/micronaut/gradle/MicronautMinimalApplicationPlugin.java:106]: Add a comment above this code to prevent this code being refactored back into a lambda

**Review by graemerocher — CHANGES_REQUESTED** [review]

**Review by graemerocher — APPROVED** [review]
